### ISSUE TITLE
adding heavy-ion quark vs gluon study 1803.03589 

### ISSUE THREAD

**Issue by rkunnawa** [iml-wg/HEPML-LivingReview#18]
Hi All, 

This is a great resource!! Thanks very much for putting this together. Please find an earlier paper on quark vs gluons using jet images and telescoping jet observables here https://arxiv.org/abs/1803.03589 that could be added. thanks again!

**Comment by bnachman** [comment]
Done!  Thank you @rkunnawa.

Sincerely,
Ben

**Comment by matthewfeickert** [comment]
I think it is more helpful if the papers are added in the BibTeX file in reverse chronological order of when they were _released_. There really isn't any interesting information contained in when we added them, as the date it totally arbitrary and can be seen from just the commit.

**Comment by bnachman** [comment]
Hi @matthewfeickert,

I agree, though I'm not sure how useful it is to have any information about the date.  People should not be browsing the .bib file and expect the order to be meaningful.  In particular, I would be in favor of dropping the date comment in the future.  Thoughts?

**Comment by matthewfeickert** [comment]
> People should not be browsing the .bib file and expect the order to be meaningful.

I think the reverse chronological ordering of the `.bib` is a feature. It makes it more human readable if you're trying to look for papers that were added in X year. Also, if you're trying to make sure that papers appear in a specific chronological order in a section this isn't hard to do if you're looking to insert a new reference in the correct order.

**Comment by bnachman** [comment]
Is this a feature we want?  To people really want to know what papers were out in a particular year?  I am not against it, but I am also not sure how this would be useful.  Also, I think if anything, the year of first post to arXiv is more useful than the most recent update, but please let me know what you have in mind for how this would be used.

**Comment by matthewfeickert** [comment]
> Is this a feature we want? To people really want to know what papers were out in a particular year?

I thought David had asked for this so that it chronology can be easily determined.

> I think if anything, the year of first post to arXiv is more useful than the most recent update.

Yeah, I would mostly agree. In the past I went with the date it got added to INSPIRE as that generally synced up with the first time there was a real publication on arXiv.

> please let me know what you have in mind for how this would be used.

Pretty much just establishing chronology in the citations in the review so that they appear in order.

**Comment by bnachman** [comment]
Thank you for moving it!  I think the order they appear in the compiled .tex though depends on the order they go in the .tex file.  This will be harder to regulate as the names don't have the year in them.

**Comment by matthewfeickert** [comment]
> I think the order they appear in the compiled .tex though depends on the order they go in the .tex file. This will be harder to regulate as the names don't have the year in them.

Correct. This is why I think it is advantageous to have the `.bib` file be in reverse chronological order (seems natural to me at least) if the goal is to have the ordering of the citations in the `.tex` be in chronological order. For example, in PR #19 it was pretty easy to look at the "quarks and gluons" section and then using reverse chronological order with dates to pop [Probing heavy ion collisions using quark and gluon jet substructure](https://inspirehep.net/literature/1659306) two spots over so that it was cited before the 2019 and 2020 papers.

I fully admit that this could take a bit of scrolling though in some cases. :) As you're doing the active work of checking the arXiv daily, what we could do is just have you do your normal commit of adding the reference and placing it in the relevant subsection, but just in a new branch so that when you push it up you can open a PR. As I'm on GitHub each night anyway doing code review I can just move the reference into order if needed and then merge the PR. Thoughts?

**Comment by bnachman** [comment]
I am happy to add in the refs in the .bib in reverse chronological order.  For now, I would prefer to not open a PR as it takes a little longer and may deter me from doing this at all.  Right now, adding the daily updates takes < 1 min so definitely below threshold.
