### ISSUE TITLE
Titles getting cut off

### ISSUE THREAD

**Issue by cranmer** [iml-wg/HEPML-LivingReview#4]
My understanding is this is because the webpages are being scraped and sometimes INSPIRE puts title on more than one line. The INSPIRE API is easy to use and would fix this problem. 

Here is an example:
https://github.com/cranmer/inspire_play/blob/master/inspire-try1.ipynb

**Comment by bnachman** [comment]
Hi @cranmer,

Thank you for the pointer!  However, most of our entries come from arXiv and then have been entered by using the expert .bib on arXiv or on INSPIRE.  Neither of these have the INSPIRE IDs in them.  Do you have a quick way of going from an arXiv number to an INSPIRE ID?  I could write some more generic web scrapping utility, but there are few enough entries that the title problem can be fixed in 5 minutes by hand.  This is not nice if we want a tool that will eventually automatically update entries, so it would be great if such a utility existed.  Thank you again!

Sincerely,
Ben

**Comment by matthewfeickert** [comment]
Resolved (for time being) by 11f7b112450f5ae7d52504ed65c2d8153bf54542
